package com.opencbs.core.services.schedulegenerators;

public enum ScheduleGeneratorTypes {

    FLAT_MONTHLY(30),
    FLAT_BIWEEKLY(15),
    FIXED_PRINCIPAL_BY_SIX_MONTH(180),
    FIXED_PRINCIPAL_SEMIANNUAL_QUARTERLY(90),
    FIXED_PRINCIPAL_QUARTERLY(90),
    FIXED_PRINCIPAL_MONTHLY(30),
    FIXED_PRINCIPAL_BIWEEKLY(15),
    DIFFERENTIAL_SEMI_ANNUAL(180),
    DIFFERENTIAL_QUARTERLY(90),
    ANNUITY_SEMIANNUALLY(180),
    ANNUITY_SEMIANNUALLY_FACT(180),
    ANNUITY_QUARTERLY(90),
    ANNUITY_QUARTERLY_FACT(90),
    ANNUITY_MONTHLY(30),
    ANNUITY_MONTHLY_FACT(30),
    ANNUITY_BIWEEKLY(15),
    FLAT_QUARTERLY(90),
    MATURITY_QUARTERLY_ACTUAL_360_DOMESTIC(90),
    FLAT_ANNUALLY(365),
    ANNUITY_TWO_MONTHLY(60),
    FLAT_BI_ANNUALLY(180),
    FLAT_TWO_MONTHLY(60),
    FIXED_PRINCIPAL_TWO_MONTHLY(60),
    MATURITY_QUARTERLY_ACTUAL_360(90),
    FIXED_PRINCIPAL_ANNUAL(365),
    ANNUITY_ANNUAL(365);

    private int days;

    ScheduleGeneratorTypes(int days) {
        this.days = days;
    }

    public int getDays() {
        return days;
    }
}